[build]
  command = "echo 'serving pre-built docs'"
  publish = "docs"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
